package com.kder.business.dao.policycompany;

import com.kder.business.entity.policycompany.PolicyCompanyDo;
import com.kder.business.entity.policycompany.PolicyCompanyExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PolicyCompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	int countByExample(PolicyCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	int deleteByExample(PolicyCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	int insert(PolicyCompanyDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	int insertSelective(PolicyCompanyDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	List<PolicyCompanyDo> selectByExample(PolicyCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	PolicyCompanyDo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	int updateByExampleSelective(@Param("record") PolicyCompanyDo record,
			@Param("example") PolicyCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	int updateByExample(@Param("record") PolicyCompanyDo record,
			@Param("example") PolicyCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	int updateByPrimaryKeySelective(PolicyCompanyDo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policy_company
	 * @mbggenerated  Sun Jun 24 10:45:25 CST 2018
	 */
	int updateByPrimaryKey(PolicyCompanyDo record);

	List<PolicyCompanyDo> queryListPage(Map<String, Object> param);
}