package com.kder.business.entity.policytype;

import java.util.Date;

public class TPolicyType implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.id
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.code
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.name
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.status
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.parentId
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private Long parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.remark
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.createUserId
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private Long createuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.updateUserId
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private Long updateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.createTime
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_policy_type.updateTime
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.id
     *
     * @return the value of t_policy_type.id
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.id
     *
     * @param id the value for t_policy_type.id
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.code
     *
     * @return the value of t_policy_type.code
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.code
     *
     * @param code the value for t_policy_type.code
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.name
     *
     * @return the value of t_policy_type.name
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.name
     *
     * @param name the value for t_policy_type.name
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.status
     *
     * @return the value of t_policy_type.status
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.status
     *
     * @param status the value for t_policy_type.status
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.parentId
     *
     * @return the value of t_policy_type.parentId
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.parentId
     *
     * @param parentid the value for t_policy_type.parentId
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.remark
     *
     * @return the value of t_policy_type.remark
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.remark
     *
     * @param remark the value for t_policy_type.remark
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.createUserId
     *
     * @return the value of t_policy_type.createUserId
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public Long getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.createUserId
     *
     * @param createuserid the value for t_policy_type.createUserId
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setCreateuserid(Long createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.updateUserId
     *
     * @return the value of t_policy_type.updateUserId
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public Long getUpdateuserid() {
        return updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.updateUserId
     *
     * @param updateuserid the value for t_policy_type.updateUserId
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setUpdateuserid(Long updateuserid) {
        this.updateuserid = updateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.createTime
     *
     * @return the value of t_policy_type.createTime
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.createTime
     *
     * @param createtime the value for t_policy_type.createTime
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_policy_type.updateTime
     *
     * @return the value of t_policy_type.updateTime
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_policy_type.updateTime
     *
     * @param updatetime the value for t_policy_type.updateTime
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}