package com.kder.business.dao.product;

import com.kder.business.entity.product.TFsInsurance;
import com.kder.business.entity.product.TFsInsuranceExample;
import com.kder.business.entity.product.TFsInsuranceWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFsInsuranceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int countByExample(TFsInsuranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int deleteByExample(TFsInsuranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int deleteByPrimaryKey(Integer insId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int insert(TFsInsuranceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int insertSelective(TFsInsuranceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    List<TFsInsuranceWithBLOBs> selectByExampleWithBLOBs(TFsInsuranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    List<TFsInsurance> selectByExample(TFsInsuranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    TFsInsuranceWithBLOBs selectByPrimaryKey(Integer insId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") TFsInsuranceWithBLOBs record, @Param("example") TFsInsuranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TFsInsuranceWithBLOBs record, @Param("example") TFsInsuranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int updateByExample(@Param("record") TFsInsurance record, @Param("example") TFsInsuranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int updateByPrimaryKeySelective(TFsInsuranceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TFsInsuranceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fs_insurance
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    int updateByPrimaryKey(TFsInsurance record);
}