package com.kder.business.dao.org;

import com.kder.business.entity.org.OrgDo;
import com.kder.business.entity.org.OrgExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface IOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    int countByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    int deleteByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    int insert(OrgDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    int insertSelective(OrgDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    List<OrgDo> selectByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    OrgDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrgDo record, @Param("example") OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    int updateByExample(@Param("record") OrgDo record, @Param("example") OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    int updateByPrimaryKeySelective(OrgDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_org
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    int updateByPrimaryKey(OrgDo record);

	List<OrgDo> queryListPage(Map<String, Object> param);
}