package com.kder.business.entity.policycompany;

import java.util.Date;

public class PolicyCompanyDo implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.id
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.policy_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String policyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.short_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.home_url
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String homeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.banner_url
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String bannerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.company_type
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String companyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.contact_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.contact_phone
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.address
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.company_reg_address
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String companyRegAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.manager_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.partner_status
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private Integer partnerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.partner_date
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private Date partnerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.status
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.create_time
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.create_by
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.update_time
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_company.update_by
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.id
     *
     * @return the value of policy_company.id
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.id
     *
     * @param id the value for policy_company.id
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.policy_name
     *
     * @return the value of policy_company.policy_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getPolicyName() {
        return policyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.policy_name
     *
     * @param policyName the value for policy_company.policy_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setPolicyName(String policyName) {
        this.policyName = policyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.short_name
     *
     * @return the value of policy_company.short_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.short_name
     *
     * @param shortName the value for policy_company.short_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.home_url
     *
     * @return the value of policy_company.home_url
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getHomeUrl() {
        return homeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.home_url
     *
     * @param homeUrl the value for policy_company.home_url
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setHomeUrl(String homeUrl) {
        this.homeUrl = homeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.banner_url
     *
     * @return the value of policy_company.banner_url
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getBannerUrl() {
        return bannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.banner_url
     *
     * @param bannerUrl the value for policy_company.banner_url
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.company_type
     *
     * @return the value of policy_company.company_type
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.company_type
     *
     * @param companyType the value for policy_company.company_type
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.contact_name
     *
     * @return the value of policy_company.contact_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.contact_name
     *
     * @param contactName the value for policy_company.contact_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.contact_phone
     *
     * @return the value of policy_company.contact_phone
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.contact_phone
     *
     * @param contactPhone the value for policy_company.contact_phone
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.address
     *
     * @return the value of policy_company.address
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.address
     *
     * @param address the value for policy_company.address
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.company_reg_address
     *
     * @return the value of policy_company.company_reg_address
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getCompanyRegAddress() {
        return companyRegAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.company_reg_address
     *
     * @param companyRegAddress the value for policy_company.company_reg_address
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setCompanyRegAddress(String companyRegAddress) {
        this.companyRegAddress = companyRegAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.manager_name
     *
     * @return the value of policy_company.manager_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.manager_name
     *
     * @param managerName the value for policy_company.manager_name
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.partner_status
     *
     * @return the value of policy_company.partner_status
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public Integer getPartnerStatus() {
        return partnerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.partner_status
     *
     * @param partnerStatus the value for policy_company.partner_status
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setPartnerStatus(Integer partnerStatus) {
        this.partnerStatus = partnerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.partner_date
     *
     * @return the value of policy_company.partner_date
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public Date getPartnerDate() {
        return partnerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.partner_date
     *
     * @param partnerDate the value for policy_company.partner_date
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setPartnerDate(Date partnerDate) {
        this.partnerDate = partnerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.status
     *
     * @return the value of policy_company.status
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.status
     *
     * @param status the value for policy_company.status
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.create_time
     *
     * @return the value of policy_company.create_time
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.create_time
     *
     * @param createTime the value for policy_company.create_time
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.create_by
     *
     * @return the value of policy_company.create_by
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.create_by
     *
     * @param createBy the value for policy_company.create_by
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.update_time
     *
     * @return the value of policy_company.update_time
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.update_time
     *
     * @param updateTime the value for policy_company.update_time
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_company.update_by
     *
     * @return the value of policy_company.update_by
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_company.update_by
     *
     * @param updateBy the value for policy_company.update_by
     *
     * @mbggenerated Sun Jun 24 10:45:25 CST 2018
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}