package com.kder.business.dao.privatecust;

import com.kder.business.entity.privatecust.CtPrivateCust;
import com.kder.business.entity.privatecust.CtPrivateCustExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CtPrivateCustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    int countByExample(CtPrivateCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    int deleteByExample(CtPrivateCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    int insert(CtPrivateCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    int insertSelective(CtPrivateCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    List<CtPrivateCust> selectByExample(CtPrivateCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    CtPrivateCust selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") CtPrivateCust record, @Param("example") CtPrivateCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    int updateByExample(@Param("record") CtPrivateCust record, @Param("example") CtPrivateCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    int updateByPrimaryKeySelective(CtPrivateCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ct_private_cust
     *
     * @mbggenerated Sat Jun 30 23:13:01 CST 2018
     */
    int updateByPrimaryKey(CtPrivateCust record);
    
    /**
     * 分页查询
     * @param param
     * @return
     */
	List<CtPrivateCust> queryListPage(Map<String, Object> param);
}