package com.kder.business.entity.user;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PeopleExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public PeopleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPeopleIdIsNull() {
            addCriterion("people_id is null");
            return (Criteria) this;
        }

        public Criteria andPeopleIdIsNotNull() {
            addCriterion("people_id is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleIdEqualTo(Integer value) {
            addCriterion("people_id =", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdNotEqualTo(Integer value) {
            addCriterion("people_id <>", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdGreaterThan(Integer value) {
            addCriterion("people_id >", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("people_id >=", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdLessThan(Integer value) {
            addCriterion("people_id <", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdLessThanOrEqualTo(Integer value) {
            addCriterion("people_id <=", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdIn(List<Integer> values) {
            addCriterion("people_id in", values, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdNotIn(List<Integer> values) {
            addCriterion("people_id not in", values, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdBetween(Integer value1, Integer value2) {
            addCriterion("people_id between", value1, value2, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("people_id not between", value1, value2, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneIsNull() {
            addCriterion("people_phone is null");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneIsNotNull() {
            addCriterion("people_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneEqualTo(String value) {
            addCriterion("people_phone =", value, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneNotEqualTo(String value) {
            addCriterion("people_phone <>", value, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneGreaterThan(String value) {
            addCriterion("people_phone >", value, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("people_phone >=", value, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneLessThan(String value) {
            addCriterion("people_phone <", value, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneLessThanOrEqualTo(String value) {
            addCriterion("people_phone <=", value, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneLike(String value) {
            addCriterion("people_phone like", value, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneNotLike(String value) {
            addCriterion("people_phone not like", value, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneIn(List<String> values) {
            addCriterion("people_phone in", values, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneNotIn(List<String> values) {
            addCriterion("people_phone not in", values, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneBetween(String value1, String value2) {
            addCriterion("people_phone between", value1, value2, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeoplePhoneNotBetween(String value1, String value2) {
            addCriterion("people_phone not between", value1, value2, "peoplePhone");
            return (Criteria) this;
        }

        public Criteria andPeopleNameIsNull() {
            addCriterion("people_name is null");
            return (Criteria) this;
        }

        public Criteria andPeopleNameIsNotNull() {
            addCriterion("people_name is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleNameEqualTo(String value) {
            addCriterion("people_name =", value, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameNotEqualTo(String value) {
            addCriterion("people_name <>", value, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameGreaterThan(String value) {
            addCriterion("people_name >", value, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameGreaterThanOrEqualTo(String value) {
            addCriterion("people_name >=", value, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameLessThan(String value) {
            addCriterion("people_name <", value, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameLessThanOrEqualTo(String value) {
            addCriterion("people_name <=", value, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameLike(String value) {
            addCriterion("people_name like", value, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameNotLike(String value) {
            addCriterion("people_name not like", value, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameIn(List<String> values) {
            addCriterion("people_name in", values, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameNotIn(List<String> values) {
            addCriterion("people_name not in", values, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameBetween(String value1, String value2) {
            addCriterion("people_name between", value1, value2, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeopleNameNotBetween(String value1, String value2) {
            addCriterion("people_name not between", value1, value2, "peopleName");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordIsNull() {
            addCriterion("people_password is null");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordIsNotNull() {
            addCriterion("people_password is not null");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordEqualTo(String value) {
            addCriterion("people_password =", value, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordNotEqualTo(String value) {
            addCriterion("people_password <>", value, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordGreaterThan(String value) {
            addCriterion("people_password >", value, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordGreaterThanOrEqualTo(String value) {
            addCriterion("people_password >=", value, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordLessThan(String value) {
            addCriterion("people_password <", value, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordLessThanOrEqualTo(String value) {
            addCriterion("people_password <=", value, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordLike(String value) {
            addCriterion("people_password like", value, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordNotLike(String value) {
            addCriterion("people_password not like", value, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordIn(List<String> values) {
            addCriterion("people_password in", values, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordNotIn(List<String> values) {
            addCriterion("people_password not in", values, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordBetween(String value1, String value2) {
            addCriterion("people_password between", value1, value2, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeoplePasswordNotBetween(String value1, String value2) {
            addCriterion("people_password not between", value1, value2, "peoplePassword");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeIsNull() {
            addCriterion("people_datetime is null");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeIsNotNull() {
            addCriterion("people_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeEqualTo(Date value) {
            addCriterion("people_datetime =", value, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeNotEqualTo(Date value) {
            addCriterion("people_datetime <>", value, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeGreaterThan(Date value) {
            addCriterion("people_datetime >", value, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("people_datetime >=", value, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeLessThan(Date value) {
            addCriterion("people_datetime <", value, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("people_datetime <=", value, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeIn(List<Date> values) {
            addCriterion("people_datetime in", values, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeNotIn(List<Date> values) {
            addCriterion("people_datetime not in", values, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeBetween(Date value1, Date value2) {
            addCriterion("people_datetime between", value1, value2, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("people_datetime not between", value1, value2, "peopleDatetime");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdIsNull() {
            addCriterion("people_app_id is null");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdIsNotNull() {
            addCriterion("people_app_id is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdEqualTo(Integer value) {
            addCriterion("people_app_id =", value, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdNotEqualTo(Integer value) {
            addCriterion("people_app_id <>", value, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdGreaterThan(Integer value) {
            addCriterion("people_app_id >", value, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("people_app_id >=", value, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdLessThan(Integer value) {
            addCriterion("people_app_id <", value, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdLessThanOrEqualTo(Integer value) {
            addCriterion("people_app_id <=", value, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdIn(List<Integer> values) {
            addCriterion("people_app_id in", values, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdNotIn(List<Integer> values) {
            addCriterion("people_app_id not in", values, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdBetween(Integer value1, Integer value2) {
            addCriterion("people_app_id between", value1, value2, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleAppIdNotBetween(Integer value1, Integer value2) {
            addCriterion("people_app_id not between", value1, value2, "peopleAppId");
            return (Criteria) this;
        }

        public Criteria andPeopleMailIsNull() {
            addCriterion("people_mail is null");
            return (Criteria) this;
        }

        public Criteria andPeopleMailIsNotNull() {
            addCriterion("people_mail is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleMailEqualTo(String value) {
            addCriterion("people_mail =", value, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailNotEqualTo(String value) {
            addCriterion("people_mail <>", value, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailGreaterThan(String value) {
            addCriterion("people_mail >", value, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailGreaterThanOrEqualTo(String value) {
            addCriterion("people_mail >=", value, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailLessThan(String value) {
            addCriterion("people_mail <", value, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailLessThanOrEqualTo(String value) {
            addCriterion("people_mail <=", value, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailLike(String value) {
            addCriterion("people_mail like", value, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailNotLike(String value) {
            addCriterion("people_mail not like", value, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailIn(List<String> values) {
            addCriterion("people_mail in", values, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailNotIn(List<String> values) {
            addCriterion("people_mail not in", values, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailBetween(String value1, String value2) {
            addCriterion("people_mail between", value1, value2, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleMailNotBetween(String value1, String value2) {
            addCriterion("people_mail not between", value1, value2, "peopleMail");
            return (Criteria) this;
        }

        public Criteria andPeopleStateIsNull() {
            addCriterion("people_state is null");
            return (Criteria) this;
        }

        public Criteria andPeopleStateIsNotNull() {
            addCriterion("people_state is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleStateEqualTo(Integer value) {
            addCriterion("people_state =", value, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleStateNotEqualTo(Integer value) {
            addCriterion("people_state <>", value, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleStateGreaterThan(Integer value) {
            addCriterion("people_state >", value, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("people_state >=", value, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleStateLessThan(Integer value) {
            addCriterion("people_state <", value, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleStateLessThanOrEqualTo(Integer value) {
            addCriterion("people_state <=", value, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleStateIn(List<Integer> values) {
            addCriterion("people_state in", values, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleStateNotIn(List<Integer> values) {
            addCriterion("people_state not in", values, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleStateBetween(Integer value1, Integer value2) {
            addCriterion("people_state between", value1, value2, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleStateNotBetween(Integer value1, Integer value2) {
            addCriterion("people_state not between", value1, value2, "peopleState");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeIsNull() {
            addCriterion("people_code is null");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeIsNotNull() {
            addCriterion("people_code is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeEqualTo(String value) {
            addCriterion("people_code =", value, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeNotEqualTo(String value) {
            addCriterion("people_code <>", value, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeGreaterThan(String value) {
            addCriterion("people_code >", value, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeGreaterThanOrEqualTo(String value) {
            addCriterion("people_code >=", value, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeLessThan(String value) {
            addCriterion("people_code <", value, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeLessThanOrEqualTo(String value) {
            addCriterion("people_code <=", value, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeLike(String value) {
            addCriterion("people_code like", value, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeNotLike(String value) {
            addCriterion("people_code not like", value, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeIn(List<String> values) {
            addCriterion("people_code in", values, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeNotIn(List<String> values) {
            addCriterion("people_code not in", values, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeBetween(String value1, String value2) {
            addCriterion("people_code between", value1, value2, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodeNotBetween(String value1, String value2) {
            addCriterion("people_code not between", value1, value2, "peopleCode");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateIsNull() {
            addCriterion("people_codesenddate is null");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateIsNotNull() {
            addCriterion("people_codesenddate is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateEqualTo(Date value) {
            addCriterion("people_codesenddate =", value, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateNotEqualTo(Date value) {
            addCriterion("people_codesenddate <>", value, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateGreaterThan(Date value) {
            addCriterion("people_codesenddate >", value, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateGreaterThanOrEqualTo(Date value) {
            addCriterion("people_codesenddate >=", value, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateLessThan(Date value) {
            addCriterion("people_codesenddate <", value, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateLessThanOrEqualTo(Date value) {
            addCriterion("people_codesenddate <=", value, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateIn(List<Date> values) {
            addCriterion("people_codesenddate in", values, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateNotIn(List<Date> values) {
            addCriterion("people_codesenddate not in", values, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateBetween(Date value1, Date value2) {
            addCriterion("people_codesenddate between", value1, value2, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeopleCodesenddateNotBetween(Date value1, Date value2) {
            addCriterion("people_codesenddate not between", value1, value2, "peopleCodesenddate");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckIsNull() {
            addCriterion("people_phonecheck is null");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckIsNotNull() {
            addCriterion("people_phonecheck is not null");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckEqualTo(Integer value) {
            addCriterion("people_phonecheck =", value, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckNotEqualTo(Integer value) {
            addCriterion("people_phonecheck <>", value, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckGreaterThan(Integer value) {
            addCriterion("people_phonecheck >", value, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckGreaterThanOrEqualTo(Integer value) {
            addCriterion("people_phonecheck >=", value, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckLessThan(Integer value) {
            addCriterion("people_phonecheck <", value, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckLessThanOrEqualTo(Integer value) {
            addCriterion("people_phonecheck <=", value, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckIn(List<Integer> values) {
            addCriterion("people_phonecheck in", values, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckNotIn(List<Integer> values) {
            addCriterion("people_phonecheck not in", values, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckBetween(Integer value1, Integer value2) {
            addCriterion("people_phonecheck between", value1, value2, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeoplePhonecheckNotBetween(Integer value1, Integer value2) {
            addCriterion("people_phonecheck not between", value1, value2, "peoplePhonecheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckIsNull() {
            addCriterion("people_maillcheck is null");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckIsNotNull() {
            addCriterion("people_maillcheck is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckEqualTo(Integer value) {
            addCriterion("people_maillcheck =", value, "peopleMaillcheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckNotEqualTo(Integer value) {
            addCriterion("people_maillcheck <>", value, "peopleMaillcheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckGreaterThan(Integer value) {
            addCriterion("people_maillcheck >", value, "peopleMaillcheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckGreaterThanOrEqualTo(Integer value) {
            addCriterion("people_maillcheck >=", value, "peopleMaillcheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckLessThan(Integer value) {
            addCriterion("people_maillcheck <", value, "peopleMaillcheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckLessThanOrEqualTo(Integer value) {
            addCriterion("people_maillcheck <=", value, "peopleMaillcheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckIn(List<Integer> values) {
            addCriterion("people_maillcheck in", values, "peopleMaillcheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckNotIn(List<Integer> values) {
            addCriterion("people_maillcheck not in", values, "peopleMaillcheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckBetween(Integer value1, Integer value2) {
            addCriterion("people_maillcheck between", value1, value2, "peopleMaillcheck");
            return (Criteria) this;
        }

        public Criteria andPeopleMaillcheckNotBetween(Integer value1, Integer value2) {
            addCriterion("people_maillcheck not between", value1, value2, "peopleMaillcheck");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table people
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 09 01:47:56 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table people
     *
     * @mbggenerated Sat Jun 09 01:47:56 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}