package com.kder.business.entity.user;

import java.util.Date;

public class People {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_id
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private Integer peopleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_phone
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private String peoplePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_name
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private String peopleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_password
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private String peoplePassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_datetime
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private Date peopleDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_app_id
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private Integer peopleAppId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_mail
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private String peopleMail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_state
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private Integer peopleState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_code
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private String peopleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_codesenddate
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private Date peopleCodesenddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_phonecheck
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private Integer peoplePhonecheck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column people.people_maillcheck
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	private Integer peopleMaillcheck;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_id
	 * @return  the value of people.people_id
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public Integer getPeopleId() {
		return peopleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_id
	 * @param peopleId  the value for people.people_id
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeopleId(Integer peopleId) {
		this.peopleId = peopleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_phone
	 * @return  the value of people.people_phone
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public String getPeoplePhone() {
		return peoplePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_phone
	 * @param peoplePhone  the value for people.people_phone
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeoplePhone(String peoplePhone) {
		this.peoplePhone = peoplePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_name
	 * @return  the value of people.people_name
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public String getPeopleName() {
		return peopleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_name
	 * @param peopleName  the value for people.people_name
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeopleName(String peopleName) {
		this.peopleName = peopleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_password
	 * @return  the value of people.people_password
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public String getPeoplePassword() {
		return peoplePassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_password
	 * @param peoplePassword  the value for people.people_password
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeoplePassword(String peoplePassword) {
		this.peoplePassword = peoplePassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_datetime
	 * @return  the value of people.people_datetime
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public Date getPeopleDatetime() {
		return peopleDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_datetime
	 * @param peopleDatetime  the value for people.people_datetime
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeopleDatetime(Date peopleDatetime) {
		this.peopleDatetime = peopleDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_app_id
	 * @return  the value of people.people_app_id
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public Integer getPeopleAppId() {
		return peopleAppId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_app_id
	 * @param peopleAppId  the value for people.people_app_id
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeopleAppId(Integer peopleAppId) {
		this.peopleAppId = peopleAppId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_mail
	 * @return  the value of people.people_mail
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public String getPeopleMail() {
		return peopleMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_mail
	 * @param peopleMail  the value for people.people_mail
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeopleMail(String peopleMail) {
		this.peopleMail = peopleMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_state
	 * @return  the value of people.people_state
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public Integer getPeopleState() {
		return peopleState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_state
	 * @param peopleState  the value for people.people_state
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeopleState(Integer peopleState) {
		this.peopleState = peopleState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_code
	 * @return  the value of people.people_code
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public String getPeopleCode() {
		return peopleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_code
	 * @param peopleCode  the value for people.people_code
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeopleCode(String peopleCode) {
		this.peopleCode = peopleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_codesenddate
	 * @return  the value of people.people_codesenddate
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public Date getPeopleCodesenddate() {
		return peopleCodesenddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_codesenddate
	 * @param peopleCodesenddate  the value for people.people_codesenddate
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeopleCodesenddate(Date peopleCodesenddate) {
		this.peopleCodesenddate = peopleCodesenddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_phonecheck
	 * @return  the value of people.people_phonecheck
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public Integer getPeoplePhonecheck() {
		return peoplePhonecheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_phonecheck
	 * @param peoplePhonecheck  the value for people.people_phonecheck
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeoplePhonecheck(Integer peoplePhonecheck) {
		this.peoplePhonecheck = peoplePhonecheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column people.people_maillcheck
	 * @return  the value of people.people_maillcheck
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public Integer getPeopleMaillcheck() {
		return peopleMaillcheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column people.people_maillcheck
	 * @param peopleMaillcheck  the value for people.people_maillcheck
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	public void setPeopleMaillcheck(Integer peopleMaillcheck) {
		this.peopleMaillcheck = peopleMaillcheck;
	}

	@Override
	public String toString() {
		return "People [peopleId=" + peopleId + ", peoplePhone=" + peoplePhone
				+ ", peopleName=" + peopleName + ", peoplePassword="
				+ peoplePassword + ", peopleDatetime=" + peopleDatetime
				+ ", peopleAppId=" + peopleAppId + ", peopleMail=" + peopleMail
				+ ", peopleState=" + peopleState + ", peopleCode=" + peopleCode
				+ ", peopleCodesenddate=" + peopleCodesenddate
				+ ", peoplePhonecheck=" + peoplePhonecheck
				+ ", peopleMaillcheck=" + peopleMaillcheck + "]";
	}
	
	
}