package com.kder.business.dao.policytype;

import com.kder.business.entity.policytype.TPolicyType;
import com.kder.business.entity.policytype.TPolicyTypeExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TPolicyTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    int countByExample(TPolicyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    int deleteByExample(TPolicyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    int insert(TPolicyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    int insertSelective(TPolicyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    List<TPolicyType> selectByExample(TPolicyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    TPolicyType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") TPolicyType record, @Param("example") TPolicyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    int updateByExample(@Param("record") TPolicyType record, @Param("example") TPolicyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    int updateByPrimaryKeySelective(TPolicyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_policy_type
     *
     * @mbggenerated Wed Jul 04 09:11:59 CST 2018
     */
    int updateByPrimaryKey(TPolicyType record);

	List<TPolicyType> selectList(Map<String, Object> param);
}