package com.kder.business.entity.org;

import java.util.Date;

public class OrgDo   implements java.io.Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.id
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.org_code
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.org_name
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.parent_id
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.status
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.create_time
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.create_by
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.update_time
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.update_by
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.id
     *
     * @return the value of t_org.id
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.id
     *
     * @param id the value for t_org.id
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.org_code
     *
     * @return the value of t_org.org_code
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.org_code
     *
     * @param orgCode the value for t_org.org_code
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.org_name
     *
     * @return the value of t_org.org_name
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.org_name
     *
     * @param orgName the value for t_org.org_name
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.parent_id
     *
     * @return the value of t_org.parent_id
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.parent_id
     *
     * @param parentId the value for t_org.parent_id
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.status
     *
     * @return the value of t_org.status
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.status
     *
     * @param status the value for t_org.status
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.create_time
     *
     * @return the value of t_org.create_time
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.create_time
     *
     * @param createTime the value for t_org.create_time
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.create_by
     *
     * @return the value of t_org.create_by
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.create_by
     *
     * @param createBy the value for t_org.create_by
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.update_time
     *
     * @return the value of t_org.update_time
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.update_time
     *
     * @param updateTime the value for t_org.update_time
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.update_by
     *
     * @return the value of t_org.update_by
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.update_by
     *
     * @param updateBy the value for t_org.update_by
     *
     * @mbggenerated Mon Jun 25 02:21:39 CST 2018
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}