package com.kder.business.dao.user;

import com.kder.business.entity.user.People;
import com.kder.business.entity.user.PeopleExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PeopleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	int countByExample(PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	int deleteByExample(PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	int deleteByPrimaryKey(Integer peopleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	int insert(People record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	int insertSelective(People record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	List<People> selectByExample(PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	People selectByPrimaryKey(Integer peopleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	int updateByExampleSelective(@Param("record") People record,
			@Param("example") PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	int updateByExample(@Param("record") People record,
			@Param("example") PeopleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	int updateByPrimaryKeySelective(People record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table people
	 * @mbggenerated  Sat Jun 09 01:47:56 CST 2018
	 */
	int updateByPrimaryKey(People record);

	List<People> getPeoplePage(Map<String, Object> param);
}