package com.kder.business.entity.order;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CtOrderExample implements java.io.Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public CtOrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	protected abstract static class GeneratedCriteria  implements java.io.Serializable{
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(Long value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(Long value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(Long value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(Long value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Long value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<Long> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<Long> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(Long value1, Long value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(Long value1, Long value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNull() {
			addCriterion("order_no is null");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNotNull() {
			addCriterion("order_no is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNoEqualTo(String value) {
			addCriterion("order_no =", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotEqualTo(String value) {
			addCriterion("order_no <>", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThan(String value) {
			addCriterion("order_no >", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("order_no >=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThan(String value) {
			addCriterion("order_no <", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThanOrEqualTo(String value) {
			addCriterion("order_no <=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLike(String value) {
			addCriterion("order_no like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotLike(String value) {
			addCriterion("order_no not like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoIn(List<String> values) {
			addCriterion("order_no in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotIn(List<String> values) {
			addCriterion("order_no not in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoBetween(String value1, String value2) {
			addCriterion("order_no between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotBetween(String value1, String value2) {
			addCriterion("order_no not between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andProdIdIsNull() {
			addCriterion("prod_id is null");
			return (Criteria) this;
		}

		public Criteria andProdIdIsNotNull() {
			addCriterion("prod_id is not null");
			return (Criteria) this;
		}

		public Criteria andProdIdEqualTo(Long value) {
			addCriterion("prod_id =", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdNotEqualTo(Long value) {
			addCriterion("prod_id <>", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdGreaterThan(Long value) {
			addCriterion("prod_id >", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdGreaterThanOrEqualTo(Long value) {
			addCriterion("prod_id >=", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdLessThan(Long value) {
			addCriterion("prod_id <", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdLessThanOrEqualTo(Long value) {
			addCriterion("prod_id <=", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdIn(List<Long> values) {
			addCriterion("prod_id in", values, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdNotIn(List<Long> values) {
			addCriterion("prod_id not in", values, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdBetween(Long value1, Long value2) {
			addCriterion("prod_id between", value1, value2, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdNotBetween(Long value1, Long value2) {
			addCriterion("prod_id not between", value1, value2, "prodId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("order_status is null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("order_status is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusEqualTo(Integer value) {
			addCriterion("order_status =", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotEqualTo(Integer value) {
			addCriterion("order_status <>", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThan(Integer value) {
			addCriterion("order_status >", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_status >=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThan(Integer value) {
			addCriterion("order_status <", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
			addCriterion("order_status <=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIn(List<Integer> values) {
			addCriterion("order_status in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotIn(List<Integer> values) {
			addCriterion("order_status not in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
			addCriterion("order_status between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("order_status not between", value1, value2,
					"orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodIsNull() {
			addCriterion("order_period is null");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodIsNotNull() {
			addCriterion("order_period is not null");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodEqualTo(String value) {
			addCriterion("order_period =", value, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodNotEqualTo(String value) {
			addCriterion("order_period <>", value, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodGreaterThan(String value) {
			addCriterion("order_period >", value, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodGreaterThanOrEqualTo(String value) {
			addCriterion("order_period >=", value, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodLessThan(String value) {
			addCriterion("order_period <", value, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodLessThanOrEqualTo(String value) {
			addCriterion("order_period <=", value, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodLike(String value) {
			addCriterion("order_period like", value, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodNotLike(String value) {
			addCriterion("order_period not like", value, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodIn(List<String> values) {
			addCriterion("order_period in", values, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodNotIn(List<String> values) {
			addCriterion("order_period not in", values, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodBetween(String value1, String value2) {
			addCriterion("order_period between", value1, value2, "orderPeriod");
			return (Criteria) this;
		}

		public Criteria andOrderPeriodNotBetween(String value1, String value2) {
			addCriterion("order_period not between", value1, value2,
					"orderPeriod");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("start_time is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("start_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Date value) {
			addCriterionForJDBCDate("start_time =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("start_time <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("start_time >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("start_time >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Date value) {
			addCriterionForJDBCDate("start_time <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("start_time <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Date> values) {
			addCriterionForJDBCDate("start_time in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("start_time not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("start_time between", value1, value2,
					"startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("start_time not between", value1, value2,
					"startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterionForJDBCDate("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterionForJDBCDate("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterionForJDBCDate("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_time between", value1, value2,
					"endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_time not between", value1, value2,
					"endTime");
			return (Criteria) this;
		}

		public Criteria andOrderAmtIsNull() {
			addCriterion("order_amt is null");
			return (Criteria) this;
		}

		public Criteria andOrderAmtIsNotNull() {
			addCriterion("order_amt is not null");
			return (Criteria) this;
		}

		public Criteria andOrderAmtEqualTo(BigDecimal value) {
			addCriterion("order_amt =", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtNotEqualTo(BigDecimal value) {
			addCriterion("order_amt <>", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtGreaterThan(BigDecimal value) {
			addCriterion("order_amt >", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("order_amt >=", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtLessThan(BigDecimal value) {
			addCriterion("order_amt <", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("order_amt <=", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtIn(List<BigDecimal> values) {
			addCriterion("order_amt in", values, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtNotIn(List<BigDecimal> values) {
			addCriterion("order_amt not in", values, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("order_amt between", value1, value2, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("order_amt not between", value1, value2, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andUserCertNoIsNull() {
			addCriterion("user_cert_no is null");
			return (Criteria) this;
		}

		public Criteria andUserCertNoIsNotNull() {
			addCriterion("user_cert_no is not null");
			return (Criteria) this;
		}

		public Criteria andUserCertNoEqualTo(String value) {
			addCriterion("user_cert_no =", value, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoNotEqualTo(String value) {
			addCriterion("user_cert_no <>", value, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoGreaterThan(String value) {
			addCriterion("user_cert_no >", value, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoGreaterThanOrEqualTo(String value) {
			addCriterion("user_cert_no >=", value, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoLessThan(String value) {
			addCriterion("user_cert_no <", value, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoLessThanOrEqualTo(String value) {
			addCriterion("user_cert_no <=", value, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoLike(String value) {
			addCriterion("user_cert_no like", value, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoNotLike(String value) {
			addCriterion("user_cert_no not like", value, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoIn(List<String> values) {
			addCriterion("user_cert_no in", values, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoNotIn(List<String> values) {
			addCriterion("user_cert_no not in", values, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoBetween(String value1, String value2) {
			addCriterion("user_cert_no between", value1, value2, "userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertNoNotBetween(String value1, String value2) {
			addCriterion("user_cert_no not between", value1, value2,
					"userCertNo");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeIsNull() {
			addCriterion("user_cert_type is null");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeIsNotNull() {
			addCriterion("user_cert_type is not null");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeEqualTo(Integer value) {
			addCriterion("user_cert_type =", value, "userCertType");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeNotEqualTo(Integer value) {
			addCriterion("user_cert_type <>", value, "userCertType");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeGreaterThan(Integer value) {
			addCriterion("user_cert_type >", value, "userCertType");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_cert_type >=", value, "userCertType");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeLessThan(Integer value) {
			addCriterion("user_cert_type <", value, "userCertType");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeLessThanOrEqualTo(Integer value) {
			addCriterion("user_cert_type <=", value, "userCertType");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeIn(List<Integer> values) {
			addCriterion("user_cert_type in", values, "userCertType");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeNotIn(List<Integer> values) {
			addCriterion("user_cert_type not in", values, "userCertType");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeBetween(Integer value1, Integer value2) {
			addCriterion("user_cert_type between", value1, value2,
					"userCertType");
			return (Criteria) this;
		}

		public Criteria andUserCertTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("user_cert_type not between", value1, value2,
					"userCertType");
			return (Criteria) this;
		}

		public Criteria andUserAddressIsNull() {
			addCriterion("user_address is null");
			return (Criteria) this;
		}

		public Criteria andUserAddressIsNotNull() {
			addCriterion("user_address is not null");
			return (Criteria) this;
		}

		public Criteria andUserAddressEqualTo(String value) {
			addCriterion("user_address =", value, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressNotEqualTo(String value) {
			addCriterion("user_address <>", value, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressGreaterThan(String value) {
			addCriterion("user_address >", value, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressGreaterThanOrEqualTo(String value) {
			addCriterion("user_address >=", value, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressLessThan(String value) {
			addCriterion("user_address <", value, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressLessThanOrEqualTo(String value) {
			addCriterion("user_address <=", value, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressLike(String value) {
			addCriterion("user_address like", value, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressNotLike(String value) {
			addCriterion("user_address not like", value, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressIn(List<String> values) {
			addCriterion("user_address in", values, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressNotIn(List<String> values) {
			addCriterion("user_address not in", values, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressBetween(String value1, String value2) {
			addCriterion("user_address between", value1, value2, "userAddress");
			return (Criteria) this;
		}

		public Criteria andUserAddressNotBetween(String value1, String value2) {
			addCriterion("user_address not between", value1, value2,
					"userAddress");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIsNull() {
			addCriterion("user_phone is null");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIsNotNull() {
			addCriterion("user_phone is not null");
			return (Criteria) this;
		}

		public Criteria andUserPhoneEqualTo(String value) {
			addCriterion("user_phone =", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotEqualTo(String value) {
			addCriterion("user_phone <>", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneGreaterThan(String value) {
			addCriterion("user_phone >", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("user_phone >=", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLessThan(String value) {
			addCriterion("user_phone <", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLessThanOrEqualTo(String value) {
			addCriterion("user_phone <=", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLike(String value) {
			addCriterion("user_phone like", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotLike(String value) {
			addCriterion("user_phone not like", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIn(List<String> values) {
			addCriterion("user_phone in", values, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotIn(List<String> values) {
			addCriterion("user_phone not in", values, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneBetween(String value1, String value2) {
			addCriterion("user_phone between", value1, value2, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotBetween(String value1, String value2) {
			addCriterion("user_phone not between", value1, value2, "userPhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameIsNull() {
			addCriterion("recognizee_name is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameIsNotNull() {
			addCriterion("recognizee_name is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameEqualTo(String value) {
			addCriterion("recognizee_name =", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameNotEqualTo(String value) {
			addCriterion("recognizee_name <>", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameGreaterThan(String value) {
			addCriterion("recognizee_name >", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameGreaterThanOrEqualTo(String value) {
			addCriterion("recognizee_name >=", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameLessThan(String value) {
			addCriterion("recognizee_name <", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameLessThanOrEqualTo(String value) {
			addCriterion("recognizee_name <=", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameLike(String value) {
			addCriterion("recognizee_name like", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameNotLike(String value) {
			addCriterion("recognizee_name not like", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameIn(List<String> values) {
			addCriterion("recognizee_name in", values, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameNotIn(List<String> values) {
			addCriterion("recognizee_name not in", values, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameBetween(String value1, String value2) {
			addCriterion("recognizee_name between", value1, value2,
					"recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameNotBetween(String value1, String value2) {
			addCriterion("recognizee_name not between", value1, value2,
					"recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthIsNull() {
			addCriterion("recognizee_birth is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthIsNotNull() {
			addCriterion("recognizee_birth is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthEqualTo(Date value) {
			addCriterionForJDBCDate("recognizee_birth =", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthNotEqualTo(Date value) {
			addCriterionForJDBCDate("recognizee_birth <>", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthGreaterThan(Date value) {
			addCriterionForJDBCDate("recognizee_birth >", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("recognizee_birth >=", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthLessThan(Date value) {
			addCriterionForJDBCDate("recognizee_birth <", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("recognizee_birth <=", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthIn(List<Date> values) {
			addCriterionForJDBCDate("recognizee_birth in", values,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthNotIn(List<Date> values) {
			addCriterionForJDBCDate("recognizee_birth not in", values,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("recognizee_birth between", value1, value2,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("recognizee_birth not between", value1,
					value2, "recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeIsNull() {
			addCriterion("recognizee_cert_type is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeIsNotNull() {
			addCriterion("recognizee_cert_type is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeEqualTo(Integer value) {
			addCriterion("recognizee_cert_type =", value, "recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeNotEqualTo(Integer value) {
			addCriterion("recognizee_cert_type <>", value, "recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeGreaterThan(Integer value) {
			addCriterion("recognizee_cert_type >", value, "recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("recognizee_cert_type >=", value, "recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeLessThan(Integer value) {
			addCriterion("recognizee_cert_type <", value, "recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeLessThanOrEqualTo(Integer value) {
			addCriterion("recognizee_cert_type <=", value, "recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeIn(List<Integer> values) {
			addCriterion("recognizee_cert_type in", values,
					"recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeNotIn(List<Integer> values) {
			addCriterion("recognizee_cert_type not in", values,
					"recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeBetween(Integer value1,
				Integer value2) {
			addCriterion("recognizee_cert_type between", value1, value2,
					"recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertTypeNotBetween(Integer value1,
				Integer value2) {
			addCriterion("recognizee_cert_type not between", value1, value2,
					"recognizeeCertType");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoIsNull() {
			addCriterion("recognizee_cert_no is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoIsNotNull() {
			addCriterion("recognizee_cert_no is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoEqualTo(String value) {
			addCriterion("recognizee_cert_no =", value, "recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoNotEqualTo(String value) {
			addCriterion("recognizee_cert_no <>", value, "recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoGreaterThan(String value) {
			addCriterion("recognizee_cert_no >", value, "recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoGreaterThanOrEqualTo(String value) {
			addCriterion("recognizee_cert_no >=", value, "recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoLessThan(String value) {
			addCriterion("recognizee_cert_no <", value, "recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoLessThanOrEqualTo(String value) {
			addCriterion("recognizee_cert_no <=", value, "recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoLike(String value) {
			addCriterion("recognizee_cert_no like", value, "recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoNotLike(String value) {
			addCriterion("recognizee_cert_no not like", value,
					"recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoIn(List<String> values) {
			addCriterion("recognizee_cert_no in", values, "recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoNotIn(List<String> values) {
			addCriterion("recognizee_cert_no not in", values,
					"recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoBetween(String value1, String value2) {
			addCriterion("recognizee_cert_no between", value1, value2,
					"recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeeCertNoNotBetween(String value1,
				String value2) {
			addCriterion("recognizee_cert_no not between", value1, value2,
					"recognizeeCertNo");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneIsNull() {
			addCriterion("recognizee_phone is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneIsNotNull() {
			addCriterion("recognizee_phone is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneEqualTo(String value) {
			addCriterion("recognizee_phone =", value, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneNotEqualTo(String value) {
			addCriterion("recognizee_phone <>", value, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneGreaterThan(String value) {
			addCriterion("recognizee_phone >", value, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneGreaterThanOrEqualTo(String value) {
			addCriterion("recognizee_phone >=", value, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneLessThan(String value) {
			addCriterion("recognizee_phone <", value, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneLessThanOrEqualTo(String value) {
			addCriterion("recognizee_phone <=", value, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneLike(String value) {
			addCriterion("recognizee_phone like", value, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneNotLike(String value) {
			addCriterion("recognizee_phone not like", value, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneIn(List<String> values) {
			addCriterion("recognizee_phone in", values, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneNotIn(List<String> values) {
			addCriterion("recognizee_phone not in", values, "recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneBetween(String value1, String value2) {
			addCriterion("recognizee_phone between", value1, value2,
					"recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeePhoneNotBetween(String value1,
				String value2) {
			addCriterion("recognizee_phone not between", value1, value2,
					"recognizeePhone");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressIsNull() {
			addCriterion("recognizee_address is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressIsNotNull() {
			addCriterion("recognizee_address is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressEqualTo(String value) {
			addCriterion("recognizee_address =", value, "recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressNotEqualTo(String value) {
			addCriterion("recognizee_address <>", value, "recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressGreaterThan(String value) {
			addCriterion("recognizee_address >", value, "recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressGreaterThanOrEqualTo(String value) {
			addCriterion("recognizee_address >=", value, "recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressLessThan(String value) {
			addCriterion("recognizee_address <", value, "recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressLessThanOrEqualTo(String value) {
			addCriterion("recognizee_address <=", value, "recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressLike(String value) {
			addCriterion("recognizee_address like", value, "recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressNotLike(String value) {
			addCriterion("recognizee_address not like", value,
					"recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressIn(List<String> values) {
			addCriterion("recognizee_address in", values, "recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressNotIn(List<String> values) {
			addCriterion("recognizee_address not in", values,
					"recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressBetween(String value1, String value2) {
			addCriterion("recognizee_address between", value1, value2,
					"recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeAddressNotBetween(String value1,
				String value2) {
			addCriterion("recognizee_address not between", value1, value2,
					"recognizeeAddress");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderIsNull() {
			addCriterion("recognizee_gender is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderIsNotNull() {
			addCriterion("recognizee_gender is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderEqualTo(String value) {
			addCriterion("recognizee_gender =", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderNotEqualTo(String value) {
			addCriterion("recognizee_gender <>", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderGreaterThan(String value) {
			addCriterion("recognizee_gender >", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderGreaterThanOrEqualTo(String value) {
			addCriterion("recognizee_gender >=", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderLessThan(String value) {
			addCriterion("recognizee_gender <", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderLessThanOrEqualTo(String value) {
			addCriterion("recognizee_gender <=", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderLike(String value) {
			addCriterion("recognizee_gender like", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderNotLike(String value) {
			addCriterion("recognizee_gender not like", value,
					"recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderIn(List<String> values) {
			addCriterion("recognizee_gender in", values, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderNotIn(List<String> values) {
			addCriterion("recognizee_gender not in", values, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderBetween(String value1, String value2) {
			addCriterion("recognizee_gender between", value1, value2,
					"recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderNotBetween(String value1,
				String value2) {
			addCriterion("recognizee_gender not between", value1, value2,
					"recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityIsNull() {
			addCriterion("recognizee_security is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityIsNotNull() {
			addCriterion("recognizee_security is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityEqualTo(String value) {
			addCriterion("recognizee_security =", value, "recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityNotEqualTo(String value) {
			addCriterion("recognizee_security <>", value, "recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityGreaterThan(String value) {
			addCriterion("recognizee_security >", value, "recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityGreaterThanOrEqualTo(String value) {
			addCriterion("recognizee_security >=", value, "recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityLessThan(String value) {
			addCriterion("recognizee_security <", value, "recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityLessThanOrEqualTo(String value) {
			addCriterion("recognizee_security <=", value, "recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityLike(String value) {
			addCriterion("recognizee_security like", value,
					"recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityNotLike(String value) {
			addCriterion("recognizee_security not like", value,
					"recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityIn(List<String> values) {
			addCriterion("recognizee_security in", values, "recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityNotIn(List<String> values) {
			addCriterion("recognizee_security not in", values,
					"recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityBetween(String value1,
				String value2) {
			addCriterion("recognizee_security between", value1, value2,
					"recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andRecognizeeSecurityNotBetween(String value1,
				String value2) {
			addCriterion("recognizee_security not between", value1, value2,
					"recognizeeSecurity");
			return (Criteria) this;
		}

		public Criteria andIsSameIsNull() {
			addCriterion("is_same is null");
			return (Criteria) this;
		}

		public Criteria andIsSameIsNotNull() {
			addCriterion("is_same is not null");
			return (Criteria) this;
		}

		public Criteria andIsSameEqualTo(String value) {
			addCriterion("is_same =", value, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameNotEqualTo(String value) {
			addCriterion("is_same <>", value, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameGreaterThan(String value) {
			addCriterion("is_same >", value, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameGreaterThanOrEqualTo(String value) {
			addCriterion("is_same >=", value, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameLessThan(String value) {
			addCriterion("is_same <", value, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameLessThanOrEqualTo(String value) {
			addCriterion("is_same <=", value, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameLike(String value) {
			addCriterion("is_same like", value, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameNotLike(String value) {
			addCriterion("is_same not like", value, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameIn(List<String> values) {
			addCriterion("is_same in", values, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameNotIn(List<String> values) {
			addCriterion("is_same not in", values, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameBetween(String value1, String value2) {
			addCriterion("is_same between", value1, value2, "isSame");
			return (Criteria) this;
		}

		public Criteria andIsSameNotBetween(String value1, String value2) {
			addCriterion("is_same not between", value1, value2, "isSame");
			return (Criteria) this;
		}

		public Criteria andSalesIdIsNull() {
			addCriterion("sales_id is null");
			return (Criteria) this;
		}

		public Criteria andSalesIdIsNotNull() {
			addCriterion("sales_id is not null");
			return (Criteria) this;
		}

		public Criteria andSalesIdEqualTo(Long value) {
			addCriterion("sales_id =", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdNotEqualTo(Long value) {
			addCriterion("sales_id <>", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdGreaterThan(Long value) {
			addCriterion("sales_id >", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdGreaterThanOrEqualTo(Long value) {
			addCriterion("sales_id >=", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdLessThan(Long value) {
			addCriterion("sales_id <", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdLessThanOrEqualTo(Long value) {
			addCriterion("sales_id <=", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdIn(List<Long> values) {
			addCriterion("sales_id in", values, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdNotIn(List<Long> values) {
			addCriterion("sales_id not in", values, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdBetween(Long value1, Long value2) {
			addCriterion("sales_id between", value1, value2, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdNotBetween(Long value1, Long value2) {
			addCriterion("sales_id not between", value1, value2, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesManIsNull() {
			addCriterion("sales_man is null");
			return (Criteria) this;
		}

		public Criteria andSalesManIsNotNull() {
			addCriterion("sales_man is not null");
			return (Criteria) this;
		}

		public Criteria andSalesManEqualTo(String value) {
			addCriterion("sales_man =", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManNotEqualTo(String value) {
			addCriterion("sales_man <>", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManGreaterThan(String value) {
			addCriterion("sales_man >", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManGreaterThanOrEqualTo(String value) {
			addCriterion("sales_man >=", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManLessThan(String value) {
			addCriterion("sales_man <", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManLessThanOrEqualTo(String value) {
			addCriterion("sales_man <=", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManLike(String value) {
			addCriterion("sales_man like", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManNotLike(String value) {
			addCriterion("sales_man not like", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManIn(List<String> values) {
			addCriterion("sales_man in", values, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManNotIn(List<String> values) {
			addCriterion("sales_man not in", values, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManBetween(String value1, String value2) {
			addCriterion("sales_man between", value1, value2, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManNotBetween(String value1, String value2) {
			addCriterion("sales_man not between", value1, value2, "salesMan");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtIsNull() {
			addCriterion("commission_amt is null");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtIsNotNull() {
			addCriterion("commission_amt is not null");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtEqualTo(BigDecimal value) {
			addCriterion("commission_amt =", value, "commissionAmt");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtNotEqualTo(BigDecimal value) {
			addCriterion("commission_amt <>", value, "commissionAmt");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtGreaterThan(BigDecimal value) {
			addCriterion("commission_amt >", value, "commissionAmt");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("commission_amt >=", value, "commissionAmt");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtLessThan(BigDecimal value) {
			addCriterion("commission_amt <", value, "commissionAmt");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("commission_amt <=", value, "commissionAmt");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtIn(List<BigDecimal> values) {
			addCriterion("commission_amt in", values, "commissionAmt");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtNotIn(List<BigDecimal> values) {
			addCriterion("commission_amt not in", values, "commissionAmt");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("commission_amt between", value1, value2,
					"commissionAmt");
			return (Criteria) this;
		}

		public Criteria andCommissionAmtNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("commission_amt not between", value1, value2,
					"commissionAmt");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNull() {
			addCriterion("project_id is null");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNotNull() {
			addCriterion("project_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjectIdEqualTo(Long value) {
			addCriterion("project_id =", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotEqualTo(Long value) {
			addCriterion("project_id <>", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThan(Long value) {
			addCriterion("project_id >", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
			addCriterion("project_id >=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThan(Long value) {
			addCriterion("project_id <", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThanOrEqualTo(Long value) {
			addCriterion("project_id <=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdIn(List<Long> values) {
			addCriterion("project_id in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotIn(List<Long> values) {
			addCriterion("project_id not in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdBetween(Long value1, Long value2) {
			addCriterion("project_id between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotBetween(Long value1, Long value2) {
			addCriterion("project_id not between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andAuditStatusIsNull() {
			addCriterion("audit_status is null");
			return (Criteria) this;
		}

		public Criteria andAuditStatusIsNotNull() {
			addCriterion("audit_status is not null");
			return (Criteria) this;
		}

		public Criteria andAuditStatusEqualTo(Integer value) {
			addCriterion("audit_status =", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotEqualTo(Integer value) {
			addCriterion("audit_status <>", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusGreaterThan(Integer value) {
			addCriterion("audit_status >", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("audit_status >=", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusLessThan(Integer value) {
			addCriterion("audit_status <", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusLessThanOrEqualTo(Integer value) {
			addCriterion("audit_status <=", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusIn(List<Integer> values) {
			addCriterion("audit_status in", values, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotIn(List<Integer> values) {
			addCriterion("audit_status not in", values, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusBetween(Integer value1, Integer value2) {
			addCriterion("audit_status between", value1, value2, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("audit_status not between", value1, value2,
					"auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditDateIsNull() {
			addCriterion("audit_date is null");
			return (Criteria) this;
		}

		public Criteria andAuditDateIsNotNull() {
			addCriterion("audit_date is not null");
			return (Criteria) this;
		}

		public Criteria andAuditDateEqualTo(Date value) {
			addCriterionForJDBCDate("audit_date =", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("audit_date <>", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateGreaterThan(Date value) {
			addCriterionForJDBCDate("audit_date >", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("audit_date >=", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateLessThan(Date value) {
			addCriterionForJDBCDate("audit_date <", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("audit_date <=", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateIn(List<Date> values) {
			addCriterionForJDBCDate("audit_date in", values, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("audit_date not in", values, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("audit_date between", value1, value2,
					"auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("audit_date not between", value1, value2,
					"auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdIsNull() {
			addCriterion("audit_instance_id is null");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdIsNotNull() {
			addCriterion("audit_instance_id is not null");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdEqualTo(Long value) {
			addCriterion("audit_instance_id =", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdNotEqualTo(Long value) {
			addCriterion("audit_instance_id <>", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdGreaterThan(Long value) {
			addCriterion("audit_instance_id >", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdGreaterThanOrEqualTo(Long value) {
			addCriterion("audit_instance_id >=", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdLessThan(Long value) {
			addCriterion("audit_instance_id <", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdLessThanOrEqualTo(Long value) {
			addCriterion("audit_instance_id <=", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdIn(List<Long> values) {
			addCriterion("audit_instance_id in", values, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdNotIn(List<Long> values) {
			addCriterion("audit_instance_id not in", values, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdBetween(Long value1, Long value2) {
			addCriterion("audit_instance_id between", value1, value2,
					"auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdNotBetween(Long value1, Long value2) {
			addCriterion("audit_instance_id not between", value1, value2,
					"auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdIsNull() {
			addCriterion("private_cust_id is null");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdIsNotNull() {
			addCriterion("private_cust_id is not null");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdEqualTo(Long value) {
			addCriterion("private_cust_id =", value, "privateCustId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdNotEqualTo(Long value) {
			addCriterion("private_cust_id <>", value, "privateCustId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdGreaterThan(Long value) {
			addCriterion("private_cust_id >", value, "privateCustId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdGreaterThanOrEqualTo(Long value) {
			addCriterion("private_cust_id >=", value, "privateCustId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdLessThan(Long value) {
			addCriterion("private_cust_id <", value, "privateCustId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdLessThanOrEqualTo(Long value) {
			addCriterion("private_cust_id <=", value, "privateCustId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdIn(List<Long> values) {
			addCriterion("private_cust_id in", values, "privateCustId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdNotIn(List<Long> values) {
			addCriterion("private_cust_id not in", values, "privateCustId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdBetween(Long value1, Long value2) {
			addCriterion("private_cust_id between", value1, value2,
					"privateCustId");
			return (Criteria) this;
		}

		public Criteria andPrivateCustIdNotBetween(Long value1, Long value2) {
			addCriterion("private_cust_id not between", value1, value2,
					"privateCustId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterionForJDBCDate("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_time between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterionForJDBCDate("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_time between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNull() {
			addCriterion("update_by is null");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNotNull() {
			addCriterion("update_by is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateByEqualTo(Long value) {
			addCriterion("update_by =", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotEqualTo(Long value) {
			addCriterion("update_by <>", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThan(Long value) {
			addCriterion("update_by >", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThanOrEqualTo(Long value) {
			addCriterion("update_by >=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThan(Long value) {
			addCriterion("update_by <", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThanOrEqualTo(Long value) {
			addCriterion("update_by <=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByIn(List<Long> values) {
			addCriterion("update_by in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotIn(List<Long> values) {
			addCriterion("update_by not in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByBetween(Long value1, Long value2) {
			addCriterion("update_by between", value1, value2, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotBetween(Long value1, Long value2) {
			addCriterion("update_by not between", value1, value2, "updateBy");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNull() {
			addCriterion("create_by is null");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNotNull() {
			addCriterion("create_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreateByEqualTo(Long value) {
			addCriterion("create_by =", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotEqualTo(Long value) {
			addCriterion("create_by <>", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThan(Long value) {
			addCriterion("create_by >", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThanOrEqualTo(Long value) {
			addCriterion("create_by >=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThan(Long value) {
			addCriterion("create_by <", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThanOrEqualTo(Long value) {
			addCriterion("create_by <=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByIn(List<Long> values) {
			addCriterion("create_by in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotIn(List<Long> values) {
			addCriterion("create_by not in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByBetween(Long value1, Long value2) {
			addCriterion("create_by between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotBetween(Long value1, Long value2) {
			addCriterion("create_by not between", value1, value2, "createBy");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ct_order
	 * @mbggenerated  Mon Jun 25 01:38:25 CST 2018
	 */
	public static class Criterion  implements java.io.Serializable{
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct_order
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 12 23:24:19 CST 2018
     */
    public static class Criteria extends GeneratedCriteria  implements java.io.Serializable{

        protected Criteria() {
            super();
        }
    }
}