package com.kder.business.entity.order;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CtOrderExample implements java.io.Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public CtOrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	protected abstract static class GeneratedCriteria implements java.io.Serializable {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(Long value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(Long value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(Long value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(Long value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Long value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<Long> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<Long> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(Long value1, Long value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(Long value1, Long value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNull() {
			addCriterion("order_no is null");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNotNull() {
			addCriterion("order_no is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNoEqualTo(String value) {
			addCriterion("order_no =", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotEqualTo(String value) {
			addCriterion("order_no <>", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThan(String value) {
			addCriterion("order_no >", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("order_no >=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThan(String value) {
			addCriterion("order_no <", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThanOrEqualTo(String value) {
			addCriterion("order_no <=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLike(String value) {
			addCriterion("order_no like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotLike(String value) {
			addCriterion("order_no not like", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoIn(List<String> values) {
			addCriterion("order_no in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotIn(List<String> values) {
			addCriterion("order_no not in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoBetween(String value1, String value2) {
			addCriterion("order_no between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotBetween(String value1, String value2) {
			addCriterion("order_no not between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andProdIdIsNull() {
			addCriterion("prod_id is null");
			return (Criteria) this;
		}

		public Criteria andProdIdIsNotNull() {
			addCriterion("prod_id is not null");
			return (Criteria) this;
		}

		public Criteria andProdIdEqualTo(Long value) {
			addCriterion("prod_id =", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdNotEqualTo(Long value) {
			addCriterion("prod_id <>", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdGreaterThan(Long value) {
			addCriterion("prod_id >", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdGreaterThanOrEqualTo(Long value) {
			addCriterion("prod_id >=", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdLessThan(Long value) {
			addCriterion("prod_id <", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdLessThanOrEqualTo(Long value) {
			addCriterion("prod_id <=", value, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdIn(List<Long> values) {
			addCriterion("prod_id in", values, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdNotIn(List<Long> values) {
			addCriterion("prod_id not in", values, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdBetween(Long value1, Long value2) {
			addCriterion("prod_id between", value1, value2, "prodId");
			return (Criteria) this;
		}

		public Criteria andProdIdNotBetween(Long value1, Long value2) {
			addCriterion("prod_id not between", value1, value2, "prodId");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Long value) {
			addCriterion("userId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Long value) {
			addCriterion("userId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Long value) {
			addCriterion("userId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Long value) {
			addCriterion("userId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Long value) {
			addCriterion("userId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Long value) {
			addCriterion("userId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Long> values) {
			addCriterion("userId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Long> values) {
			addCriterion("userId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Long value1, Long value2) {
			addCriterion("userId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Long value1, Long value2) {
			addCriterion("userId not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("order_status is null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("order_status is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusEqualTo(Integer value) {
			addCriterion("order_status =", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotEqualTo(Integer value) {
			addCriterion("order_status <>", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThan(Integer value) {
			addCriterion("order_status >", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_status >=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThan(Integer value) {
			addCriterion("order_status <", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
			addCriterion("order_status <=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIn(List<Integer> values) {
			addCriterion("order_status in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotIn(List<Integer> values) {
			addCriterion("order_status not in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
			addCriterion("order_status between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("order_status not between", value1, value2,
					"orderStatus");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("start_time is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("start_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Date value) {
			addCriterionForJDBCDate("start_time =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("start_time <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("start_time >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("start_time >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Date value) {
			addCriterionForJDBCDate("start_time <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("start_time <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Date> values) {
			addCriterionForJDBCDate("start_time in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("start_time not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("start_time between", value1, value2,
					"startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("start_time not between", value1, value2,
					"startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterionForJDBCDate("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterionForJDBCDate("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterionForJDBCDate("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_time between", value1, value2,
					"endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_time not between", value1, value2,
					"endTime");
			return (Criteria) this;
		}

		public Criteria andOrderAmtIsNull() {
			addCriterion("order_amt is null");
			return (Criteria) this;
		}

		public Criteria andOrderAmtIsNotNull() {
			addCriterion("order_amt is not null");
			return (Criteria) this;
		}

		public Criteria andOrderAmtEqualTo(BigDecimal value) {
			addCriterion("order_amt =", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtNotEqualTo(BigDecimal value) {
			addCriterion("order_amt <>", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtGreaterThan(BigDecimal value) {
			addCriterion("order_amt >", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("order_amt >=", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtLessThan(BigDecimal value) {
			addCriterion("order_amt <", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("order_amt <=", value, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtIn(List<BigDecimal> values) {
			addCriterion("order_amt in", values, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtNotIn(List<BigDecimal> values) {
			addCriterion("order_amt not in", values, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("order_amt between", value1, value2, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andOrderAmtNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("order_amt not between", value1, value2, "orderAmt");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameIsNull() {
			addCriterion("recognizee_name is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameIsNotNull() {
			addCriterion("recognizee_name is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameEqualTo(String value) {
			addCriterion("recognizee_name =", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameNotEqualTo(String value) {
			addCriterion("recognizee_name <>", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameGreaterThan(String value) {
			addCriterion("recognizee_name >", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameGreaterThanOrEqualTo(String value) {
			addCriterion("recognizee_name >=", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameLessThan(String value) {
			addCriterion("recognizee_name <", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameLessThanOrEqualTo(String value) {
			addCriterion("recognizee_name <=", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameLike(String value) {
			addCriterion("recognizee_name like", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameNotLike(String value) {
			addCriterion("recognizee_name not like", value, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameIn(List<String> values) {
			addCriterion("recognizee_name in", values, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameNotIn(List<String> values) {
			addCriterion("recognizee_name not in", values, "recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameBetween(String value1, String value2) {
			addCriterion("recognizee_name between", value1, value2,
					"recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeNameNotBetween(String value1, String value2) {
			addCriterion("recognizee_name not between", value1, value2,
					"recognizeeName");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthIsNull() {
			addCriterion("recognizee_birth is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthIsNotNull() {
			addCriterion("recognizee_birth is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthEqualTo(Date value) {
			addCriterionForJDBCDate("recognizee_birth =", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthNotEqualTo(Date value) {
			addCriterionForJDBCDate("recognizee_birth <>", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthGreaterThan(Date value) {
			addCriterionForJDBCDate("recognizee_birth >", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("recognizee_birth >=", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthLessThan(Date value) {
			addCriterionForJDBCDate("recognizee_birth <", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("recognizee_birth <=", value,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthIn(List<Date> values) {
			addCriterionForJDBCDate("recognizee_birth in", values,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthNotIn(List<Date> values) {
			addCriterionForJDBCDate("recognizee_birth not in", values,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("recognizee_birth between", value1, value2,
					"recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeBirthNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("recognizee_birth not between", value1,
					value2, "recognizeeBirth");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderIsNull() {
			addCriterion("recognizee_gender is null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderIsNotNull() {
			addCriterion("recognizee_gender is not null");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderEqualTo(String value) {
			addCriterion("recognizee_gender =", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderNotEqualTo(String value) {
			addCriterion("recognizee_gender <>", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderGreaterThan(String value) {
			addCriterion("recognizee_gender >", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderGreaterThanOrEqualTo(String value) {
			addCriterion("recognizee_gender >=", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderLessThan(String value) {
			addCriterion("recognizee_gender <", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderLessThanOrEqualTo(String value) {
			addCriterion("recognizee_gender <=", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderLike(String value) {
			addCriterion("recognizee_gender like", value, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderNotLike(String value) {
			addCriterion("recognizee_gender not like", value,
					"recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderIn(List<String> values) {
			addCriterion("recognizee_gender in", values, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderNotIn(List<String> values) {
			addCriterion("recognizee_gender not in", values, "recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderBetween(String value1, String value2) {
			addCriterion("recognizee_gender between", value1, value2,
					"recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andRecognizeeGenderNotBetween(String value1,
				String value2) {
			addCriterion("recognizee_gender not between", value1, value2,
					"recognizeeGender");
			return (Criteria) this;
		}

		public Criteria andSalesIdIsNull() {
			addCriterion("sales_id is null");
			return (Criteria) this;
		}

		public Criteria andSalesIdIsNotNull() {
			addCriterion("sales_id is not null");
			return (Criteria) this;
		}

		public Criteria andSalesIdEqualTo(Long value) {
			addCriterion("sales_id =", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdNotEqualTo(Long value) {
			addCriterion("sales_id <>", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdGreaterThan(Long value) {
			addCriterion("sales_id >", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdGreaterThanOrEqualTo(Long value) {
			addCriterion("sales_id >=", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdLessThan(Long value) {
			addCriterion("sales_id <", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdLessThanOrEqualTo(Long value) {
			addCriterion("sales_id <=", value, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdIn(List<Long> values) {
			addCriterion("sales_id in", values, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdNotIn(List<Long> values) {
			addCriterion("sales_id not in", values, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdBetween(Long value1, Long value2) {
			addCriterion("sales_id between", value1, value2, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesIdNotBetween(Long value1, Long value2) {
			addCriterion("sales_id not between", value1, value2, "salesId");
			return (Criteria) this;
		}

		public Criteria andSalesManIsNull() {
			addCriterion("sales_man is null");
			return (Criteria) this;
		}

		public Criteria andSalesManIsNotNull() {
			addCriterion("sales_man is not null");
			return (Criteria) this;
		}

		public Criteria andSalesManEqualTo(String value) {
			addCriterion("sales_man =", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManNotEqualTo(String value) {
			addCriterion("sales_man <>", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManGreaterThan(String value) {
			addCriterion("sales_man >", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManGreaterThanOrEqualTo(String value) {
			addCriterion("sales_man >=", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManLessThan(String value) {
			addCriterion("sales_man <", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManLessThanOrEqualTo(String value) {
			addCriterion("sales_man <=", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManLike(String value) {
			addCriterion("sales_man like", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManNotLike(String value) {
			addCriterion("sales_man not like", value, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManIn(List<String> values) {
			addCriterion("sales_man in", values, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManNotIn(List<String> values) {
			addCriterion("sales_man not in", values, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManBetween(String value1, String value2) {
			addCriterion("sales_man between", value1, value2, "salesMan");
			return (Criteria) this;
		}

		public Criteria andSalesManNotBetween(String value1, String value2) {
			addCriterion("sales_man not between", value1, value2, "salesMan");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNull() {
			addCriterion("project_id is null");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNotNull() {
			addCriterion("project_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjectIdEqualTo(Long value) {
			addCriterion("project_id =", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotEqualTo(Long value) {
			addCriterion("project_id <>", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThan(Long value) {
			addCriterion("project_id >", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
			addCriterion("project_id >=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThan(Long value) {
			addCriterion("project_id <", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThanOrEqualTo(Long value) {
			addCriterion("project_id <=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdIn(List<Long> values) {
			addCriterion("project_id in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotIn(List<Long> values) {
			addCriterion("project_id not in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdBetween(Long value1, Long value2) {
			addCriterion("project_id between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotBetween(Long value1, Long value2) {
			addCriterion("project_id not between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andAuditStatusIsNull() {
			addCriterion("audit_status is null");
			return (Criteria) this;
		}

		public Criteria andAuditStatusIsNotNull() {
			addCriterion("audit_status is not null");
			return (Criteria) this;
		}

		public Criteria andAuditStatusEqualTo(Integer value) {
			addCriterion("audit_status =", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotEqualTo(Integer value) {
			addCriterion("audit_status <>", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusGreaterThan(Integer value) {
			addCriterion("audit_status >", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("audit_status >=", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusLessThan(Integer value) {
			addCriterion("audit_status <", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusLessThanOrEqualTo(Integer value) {
			addCriterion("audit_status <=", value, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusIn(List<Integer> values) {
			addCriterion("audit_status in", values, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotIn(List<Integer> values) {
			addCriterion("audit_status not in", values, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusBetween(Integer value1, Integer value2) {
			addCriterion("audit_status between", value1, value2, "auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("audit_status not between", value1, value2,
					"auditStatus");
			return (Criteria) this;
		}

		public Criteria andAuditDateIsNull() {
			addCriterion("audit_date is null");
			return (Criteria) this;
		}

		public Criteria andAuditDateIsNotNull() {
			addCriterion("audit_date is not null");
			return (Criteria) this;
		}

		public Criteria andAuditDateEqualTo(Date value) {
			addCriterionForJDBCDate("audit_date =", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("audit_date <>", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateGreaterThan(Date value) {
			addCriterionForJDBCDate("audit_date >", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("audit_date >=", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateLessThan(Date value) {
			addCriterionForJDBCDate("audit_date <", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("audit_date <=", value, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateIn(List<Date> values) {
			addCriterionForJDBCDate("audit_date in", values, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("audit_date not in", values, "auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("audit_date between", value1, value2,
					"auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("audit_date not between", value1, value2,
					"auditDate");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdIsNull() {
			addCriterion("audit_instance_id is null");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdIsNotNull() {
			addCriterion("audit_instance_id is not null");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdEqualTo(Long value) {
			addCriterion("audit_instance_id =", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdNotEqualTo(Long value) {
			addCriterion("audit_instance_id <>", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdGreaterThan(Long value) {
			addCriterion("audit_instance_id >", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdGreaterThanOrEqualTo(Long value) {
			addCriterion("audit_instance_id >=", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdLessThan(Long value) {
			addCriterion("audit_instance_id <", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdLessThanOrEqualTo(Long value) {
			addCriterion("audit_instance_id <=", value, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdIn(List<Long> values) {
			addCriterion("audit_instance_id in", values, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdNotIn(List<Long> values) {
			addCriterion("audit_instance_id not in", values, "auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdBetween(Long value1, Long value2) {
			addCriterion("audit_instance_id between", value1, value2,
					"auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andAuditInstanceIdNotBetween(Long value1, Long value2) {
			addCriterion("audit_instance_id not between", value1, value2,
					"auditInstanceId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterionForJDBCDate("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_time between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterionForJDBCDate("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_time between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ct_order
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public static class Criterion implements java.io.Serializable {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ct_order
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 12 23:24:19 CST 2018
     */
    public static class Criteria extends GeneratedCriteria  implements java.io.Serializable{

        protected Criteria() {
            super();
        }
    }
}