package com.kder.business.entity.order;

import java.math.BigDecimal;
import java.util.Date;

public class CtOrder implements java.io.Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.order_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Long orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.order_no
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private String orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.prod_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Long prodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.userId
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.order_status
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Integer orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.start_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.end_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.order_amt
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private BigDecimal orderAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.recognizee_name
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private String recognizeeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.recognizee_birth
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Date recognizeeBirth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.recognizee_gender
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private String recognizeeGender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.sales_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Long salesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.sales_man
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private String salesMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.project_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Long projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.audit_status
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Integer auditStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.audit_date
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Date auditDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.audit_instance_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Long auditInstanceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.create_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ct_order.update_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.order_id
	 * @return  the value of ct_order.order_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.order_id
	 * @param orderId  the value for ct_order.order_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.order_no
	 * @return  the value of ct_order.order_no
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.order_no
	 * @param orderNo  the value for ct_order.order_no
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.prod_id
	 * @return  the value of ct_order.prod_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Long getProdId() {
		return prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.prod_id
	 * @param prodId  the value for ct_order.prod_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setProdId(Long prodId) {
		this.prodId = prodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.userId
	 * @return  the value of ct_order.userId
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.userId
	 * @param userid  the value for ct_order.userId
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.order_status
	 * @return  the value of ct_order.order_status
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Integer getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.order_status
	 * @param orderStatus  the value for ct_order.order_status
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.start_time
	 * @return  the value of ct_order.start_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.start_time
	 * @param startTime  the value for ct_order.start_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.end_time
	 * @return  the value of ct_order.end_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.end_time
	 * @param endTime  the value for ct_order.end_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.order_amt
	 * @return  the value of ct_order.order_amt
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public BigDecimal getOrderAmt() {
		return orderAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.order_amt
	 * @param orderAmt  the value for ct_order.order_amt
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setOrderAmt(BigDecimal orderAmt) {
		this.orderAmt = orderAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.recognizee_name
	 * @return  the value of ct_order.recognizee_name
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public String getRecognizeeName() {
		return recognizeeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.recognizee_name
	 * @param recognizeeName  the value for ct_order.recognizee_name
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setRecognizeeName(String recognizeeName) {
		this.recognizeeName = recognizeeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.recognizee_birth
	 * @return  the value of ct_order.recognizee_birth
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Date getRecognizeeBirth() {
		return recognizeeBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.recognizee_birth
	 * @param recognizeeBirth  the value for ct_order.recognizee_birth
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setRecognizeeBirth(Date recognizeeBirth) {
		this.recognizeeBirth = recognizeeBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.recognizee_gender
	 * @return  the value of ct_order.recognizee_gender
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public String getRecognizeeGender() {
		return recognizeeGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.recognizee_gender
	 * @param recognizeeGender  the value for ct_order.recognizee_gender
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setRecognizeeGender(String recognizeeGender) {
		this.recognizeeGender = recognizeeGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.sales_id
	 * @return  the value of ct_order.sales_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Long getSalesId() {
		return salesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.sales_id
	 * @param salesId  the value for ct_order.sales_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setSalesId(Long salesId) {
		this.salesId = salesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.sales_man
	 * @return  the value of ct_order.sales_man
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public String getSalesMan() {
		return salesMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.sales_man
	 * @param salesMan  the value for ct_order.sales_man
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setSalesMan(String salesMan) {
		this.salesMan = salesMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.project_id
	 * @return  the value of ct_order.project_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Long getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.project_id
	 * @param projectId  the value for ct_order.project_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.audit_status
	 * @return  the value of ct_order.audit_status
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Integer getAuditStatus() {
		return auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.audit_status
	 * @param auditStatus  the value for ct_order.audit_status
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setAuditStatus(Integer auditStatus) {
		this.auditStatus = auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.audit_date
	 * @return  the value of ct_order.audit_date
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Date getAuditDate() {
		return auditDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.audit_date
	 * @param auditDate  the value for ct_order.audit_date
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.audit_instance_id
	 * @return  the value of ct_order.audit_instance_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Long getAuditInstanceId() {
		return auditInstanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.audit_instance_id
	 * @param auditInstanceId  the value for ct_order.audit_instance_id
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setAuditInstanceId(Long auditInstanceId) {
		this.auditInstanceId = auditInstanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.create_time
	 * @return  the value of ct_order.create_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.create_time
	 * @param createTime  the value for ct_order.create_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ct_order.update_time
	 * @return  the value of ct_order.update_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ct_order.update_time
	 * @param updateTime  the value for ct_order.update_time
	 * @mbggenerated  Tue Jun 12 23:30:47 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}