package com.kder.business.entity.product;

import java.math.BigDecimal;
import java.util.Date;

public class TFsInsurance implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.ins_id
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private Integer insId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.title
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.company_id
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.property
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.link_url
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.ins_type
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private Integer insType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.keyword
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.soruce
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String soruce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.sort
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.start_price
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private BigDecimal startPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.hit_number
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private Integer hitNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.sale_number
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private Integer saleNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.create_date
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.update_date
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.create_by
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.update_by
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.del
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private Integer del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.small_image
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String smallImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.ins_id
     *
     * @return the value of t_fs_insurance.ins_id
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public Integer getInsId() {
        return insId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.ins_id
     *
     * @param insId the value for t_fs_insurance.ins_id
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setInsId(Integer insId) {
        this.insId = insId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.title
     *
     * @return the value of t_fs_insurance.title
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.title
     *
     * @param title the value for t_fs_insurance.title
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.company_id
     *
     * @return the value of t_fs_insurance.company_id
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.company_id
     *
     * @param companyId the value for t_fs_insurance.company_id
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.property
     *
     * @return the value of t_fs_insurance.property
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.property
     *
     * @param property the value for t_fs_insurance.property
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setProperty(String property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.link_url
     *
     * @return the value of t_fs_insurance.link_url
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.link_url
     *
     * @param linkUrl the value for t_fs_insurance.link_url
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.ins_type
     *
     * @return the value of t_fs_insurance.ins_type
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public Integer getInsType() {
        return insType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.ins_type
     *
     * @param insType the value for t_fs_insurance.ins_type
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setInsType(Integer insType) {
        this.insType = insType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.keyword
     *
     * @return the value of t_fs_insurance.keyword
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.keyword
     *
     * @param keyword the value for t_fs_insurance.keyword
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.soruce
     *
     * @return the value of t_fs_insurance.soruce
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getSoruce() {
        return soruce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.soruce
     *
     * @param soruce the value for t_fs_insurance.soruce
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setSoruce(String soruce) {
        this.soruce = soruce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.sort
     *
     * @return the value of t_fs_insurance.sort
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.sort
     *
     * @param sort the value for t_fs_insurance.sort
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.start_price
     *
     * @return the value of t_fs_insurance.start_price
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public BigDecimal getStartPrice() {
        return startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.start_price
     *
     * @param startPrice the value for t_fs_insurance.start_price
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setStartPrice(BigDecimal startPrice) {
        this.startPrice = startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.hit_number
     *
     * @return the value of t_fs_insurance.hit_number
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public Integer getHitNumber() {
        return hitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.hit_number
     *
     * @param hitNumber the value for t_fs_insurance.hit_number
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setHitNumber(Integer hitNumber) {
        this.hitNumber = hitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.sale_number
     *
     * @return the value of t_fs_insurance.sale_number
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public Integer getSaleNumber() {
        return saleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.sale_number
     *
     * @param saleNumber the value for t_fs_insurance.sale_number
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setSaleNumber(Integer saleNumber) {
        this.saleNumber = saleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.create_date
     *
     * @return the value of t_fs_insurance.create_date
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.create_date
     *
     * @param createDate the value for t_fs_insurance.create_date
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.update_date
     *
     * @return the value of t_fs_insurance.update_date
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.update_date
     *
     * @param updateDate the value for t_fs_insurance.update_date
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.create_by
     *
     * @return the value of t_fs_insurance.create_by
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.create_by
     *
     * @param createBy the value for t_fs_insurance.create_by
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.update_by
     *
     * @return the value of t_fs_insurance.update_by
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.update_by
     *
     * @param updateBy the value for t_fs_insurance.update_by
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.del
     *
     * @return the value of t_fs_insurance.del
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.del
     *
     * @param del the value for t_fs_insurance.del
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.small_image
     *
     * @return the value of t_fs_insurance.small_image
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getSmallImage() {
        return smallImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.small_image
     *
     * @param smallImage the value for t_fs_insurance.small_image
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setSmallImage(String smallImage) {
        this.smallImage = smallImage;
    }
}