package com.kder.business.entity.product;

public class TFsInsuranceWithBLOBs extends TFsInsurance implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.content
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.notice
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String notice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.helptext
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String helptext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fs_insurance.synopsis
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    private String synopsis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.content
     *
     * @return the value of t_fs_insurance.content
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.content
     *
     * @param content the value for t_fs_insurance.content
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.notice
     *
     * @return the value of t_fs_insurance.notice
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.notice
     *
     * @param notice the value for t_fs_insurance.notice
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setNotice(String notice) {
        this.notice = notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.helptext
     *
     * @return the value of t_fs_insurance.helptext
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getHelptext() {
        return helptext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.helptext
     *
     * @param helptext the value for t_fs_insurance.helptext
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setHelptext(String helptext) {
        this.helptext = helptext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fs_insurance.synopsis
     *
     * @return the value of t_fs_insurance.synopsis
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public String getSynopsis() {
        return synopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fs_insurance.synopsis
     *
     * @param synopsis the value for t_fs_insurance.synopsis
     *
     * @mbggenerated Tue Jul 03 17:17:37 CST 2018
     */
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }
}